import type {Metadata} from "next";
import "./globals.css";
import Footer from "@/components/layout/Footer"
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body className="min-h-full flex flex-col">
            <Header/>
            <main>{children}</main>
            <Footer/>
        </body>
        </html>
    );
}
